
language: cpp
compiler: gcc
os: linux
dist: bionic

before_install:
  - >
    sudo apt-get -y install
    libwebsockets-dev
    libmicrohttpd-dev
    libsnappy-dev
    libuuid1

install:
  - git clone --branch=cont_c https://github.com/izuzanak/cont.git ~/build/izuzanak/cont_c

  - cd ~/build/izuzanak/cont_c/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/izuzanak/clib/build
  - cmake ..
  - make

  - mkdir -p /dev/shm/{run,log}
  - make test

