
language: cpp
compiler: gcc
os: linux
dist: bionic

env:
  global:
    - CODECOV_TOKEN="4134880c-826c-4460-8664-8261182044c3"

before_install:
  - >
    sudo apt-get -y install
    libwebsockets-dev
    libmicrohttpd-dev
    libsnappy-dev
    libuuid1

  - pip install --user cpp-coveralls

install:
  - git clone --branch=cont_c https://github.com/izuzanak/cont.git ~/build/izuzanak/cont_c

  - cd ~/build/izuzanak/cont_c/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/izuzanak/clib/build
  - cmake -DCMAKE_BUILD_TYPE="Debug" ..
  - make

  - mkdir -p /dev/shm/{run,log}
  - make test

after_success:
  - coveralls --gcov-options '\-lp'
  - bash <(curl -s https://codecov.io/bash)

